# Generated by Django 5.0.4 on 2024-04-29 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(default='0000000000', max_length=10, verbose_name='Teléfono')),
                ('period', models.CharField(default='6', max_length=20, verbose_name='Periodo')),
                ('group', models.CharField(default='A', max_length=2, verbose_name='Grupo')),
                ('nss', models.CharField(default='000000000', max_length=20, verbose_name='Número de Seguridad Social')),
                ('payed', models.CharField(default='6', max_length=20, verbose_name='Pagado Hasta')),
                ('title_contact', models.CharField(default='LIC', max_length=20, verbose_name='Título')),
                ('full_name_contact', models.CharField(default='', max_length=100, verbose_name='Nombre Completo')),
                ('position_contact', models.CharField(default='DIRECTOR', max_length=150, verbose_name='Cargo')),
                ('in_catalog', models.BooleanField(default=False, verbose_name='Empresa en Catálogo')),
                ('title_external', models.CharField(default='LIC', max_length=20, verbose_name='Título de Asesor Externo')),
                ('full_name_external', models.CharField(default='', max_length=100, verbose_name='Nombre Asesor Externo')),
                ('position_external', models.CharField(default='DIRECTOR', max_length=150, verbose_name='Cargo de Asesor Externo')),
                ('name_project', models.CharField(default='', max_length=150, verbose_name='Nombre del Proyecto')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Fin')),
                ('period_stay', models.CharField(default='MAYO - AGOSTO', max_length=50, verbose_name='Periodo de Estancia')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('modality', models.CharField(default='PRESENCIAL', max_length=150, verbose_name='Modalidad')),
                ('line', models.CharField(default='EDUCACIÓN', max_length=150, verbose_name='Giro')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('internal_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Asesor Interno')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.student', verbose_name='Estudiante')),
            ],
        ),
    ]
