# Generated by Django 5.0.4 on 2024-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='enterprice',
            field=models.CharField(default='ACME AC', max_length=150, verbose_name='Empresa'),
        ),
    ]
